name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Add upstream repository and fetch
        run: |
          git remote add upstream https://github.com/YunaiV/ruoyi-vue-pro.git
          git fetch upstream master master-jdk17
      
      - name: Sync master branch
        run: |
          # Switch to master branch
          git checkout master
          
          # Store current workflow file changes
          git stash push .github/workflows/sync.yml || true
          
          # Try to merge upstream changes
          git merge upstream/master --no-edit || true
          
          # Restore workflow file
          git stash pop || true
          
          # Add changes and commit
          git add .
          git commit -m "Merge upstream master branch while preserving workflow" || echo "No changes to commit"
          
          # Push changes
          git push origin master
      
      - name: Sync master-jdk17 branch
        run: |
          # Switch to master-jdk17 branch
          git checkout master-jdk17 || git checkout -b master-jdk17
          
          # Store current workflow file changes
          git stash push .github/workflows/sync.yml || true
          
          # Try to merge upstream changes
          git merge upstream/master-jdk17 --no-edit || true
          
          # Restore workflow file
          git stash pop || true
          
          # Add changes and commit
          git add .
          git commit -m "Merge upstream master-jdk17 branch while preserving workflow" || echo "No changes to commit"
          
          # Push changes
          git push origin master-jdk17
